training_output: l2_train_example

cp_id: -1
target_length: 100000

meta:
  author: New User
  title: Training Report
  keywords: [example]

template_text: |
 {@ising_observables_table@}

actions_:
  - report(main=True)