training_output: l6_train_example

cp_id: -1
target_length: 10000

meta:
  author: Joe
  title: Training Report
  keywords: [example]

template_text: |
 {@plot_corr_errors@}
 {@plot_zero_momentum_green_function@}
 {@plot_effective_pole_mass@}
 {@ising_observables_table@}
 {@plot_G_autocorr@}
 {@plot_corr_errors@}
 {@plot_zero_momentum_green_function@}
 {@plot_effective_pole_mass@}

actions_:
  - report(main=True)
